ImsManager: Add updateImsServiceConfig method back
* required for MTK IMS

12-13 20:08:14.640  5672  5672 E AndroidRuntime: FATAL EXCEPTION: main
12-13 20:08:14.640  5672  5672 E AndroidRuntime: Process: com.mediatek.ims, PID: 5672
12-13 20:08:14.640  5672  5672 E AndroidRuntime: java.lang.NoSuchMethodError: No static method updateImsServiceConfig(Landroid/content/Context;IZ)V in class Lcom/android/ims/ImsManager; or its super classes (declaration of 'com.android.ims.ImsManager' appears in /system/framework/ims-common.jar)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at com.mediatek.ims.plugin.impl.ImsManagerOemPluginBase.updateImsServiceConfig(ImsManagerOemPluginBase.java:64)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at com.mediatek.ims.ImsService.updateRadioState(ImsService.java:1320)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at com.mediatek.ims.ImsService$MyHandler.handleMessage(ImsService.java:2365)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7840)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
12-13 20:08:14.640  5672  5672 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Change-Id: I3dd66d436629d37c8ec795df6569736195ae570e
Signed-off-by: SamarV-121 <samarvispute121@pm.me>